{% set version = "1.0.6" %}

package:
  name: spglm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spglm/spglm-{{ version }}.tar.gz
  sha256: b5e7b5e7ccdb4d0cf64ace03af28de8b4633aff42b2b86bc5e879f16c33634df

build:
  number: 0
  # is pure python, uses 2to3, and depends on libpysal that is py3k only!
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - libpysal
    - numpy
    - scipy
    - spreg

test:
  imports:
    - spglm

about:
  home: https://github.com/pysal/spglm
  license: BSD-3-Clause
  # https://github.com/pysal/spglm/issues/10
  # license_file: 
  summary: Sparse generalized linear models

extra:
  recipe-maintainers:
    - ocefpaf
